#!/bin/bash

OUTPUT=/tmp/docker-gitlab-runner-test

assert()
{
    echo "== assert: '$@'"

    eval "$@"
    if [ $? -ne 0 ];
    then
        echo "== test failed: '$@'"
        exit 1
    fi

    echo "== test passed"
}

# stdout of $2.. should matches $1
assertMatch()
{
    local pattern=$1
    shift

    echo "== assertMatch: '$pattern' of '$@'"

    eval "$@" 2>&1 | tee $OUTPUT
    if ! grep -q "$pattern" $OUTPUT;
    then
        echo "== test failed: '$@'"
        exit 1
    fi

    echo "== test passed"
}

assert docker build -t quanlong/gitlab-runner:latest .

assertMatch "Registering runner... forbidden (check registration token)" \
    docker run --rm -e "CI_SERVER_URL=https://gitlab.com" -e "REGISTRATION_TOKEN=xxxxxx" quanlong/gitlab-runner

assertMatch "Version:      11.1.0" \
    docker run --rm --entrypoint=gitlab-ci-multi-runner quanlong/gitlab-runner --version

# Test volume is exported at /etc/gitlab-runner
docker run --entrypoint=/bin/touch --name gitlab-test-volume quanlong/gitlab-runner /etc/gitlab-runner/config.toml
assert docker run --rm --volumes-from=gitlab-test-volume alpine cat /etc/gitlab-runner/config.toml
docker rm -f gitlab-test-volume
